In [ ]:
Q1. What is the relationship between polynomial functions and kernel functions in machine learning
algorithms?

Kernel Functions:
     In SVMs, a kernel function is a mathematical function that computes the similarity between pairs of data points in the input space. 
     SVMs use this similarity measure to map the input data into a higher-dimensional feature space.
Polynomial Kernel:    
   The polynomial kernel is a specific type of kernel function commonly used in SVMs. It is defined as 
   K(x,y)=(x⋅y+c)^d
    where,
      x and y are the input vectors
     c is a constant
     d is the degree of the polynomial
        
the relationship between polynomial functions and kernel functions in machine learning, particularly in SVMs, is that the polynomial kernel serves as a way to implicitly apply a polynomial transformation to the input data, allowing for the discovery of nonlinear decision boundaries in a higher-dimensional space. 
This facilitates the handling of more complex relationships in the data that may not be linearly separable in the original input space.

In [ ]:
Q2. How can we implement an SVM with a polynomial kernel in Python using Scikit-learn?

In [18]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [19]:
from sklearn.datasets import make_classification

In [20]:
x,y = make_classification(n_samples = 100,n_features = 2,n_classes = 2,n_clusters_per_class = 2,n_redundant = 0)

In [21]:
x

array([[-1.27504485,  1.08767536],
       [ 1.20803992,  1.31363183],
       [-0.92170353,  1.22882205],
       [-0.72144086,  2.44982522],
       [ 0.55321372,  0.93214164],
       [ 1.4244102 ,  1.66694584],
       [-0.59543445, -0.65222186],
       [ 1.34455142,  1.20946882],
       [-1.45846231, -0.13145194],
       [-1.97630546, -1.17946953],
       [-1.09171047,  0.72347664],
       [ 1.59906828,  1.32303942],
       [ 1.79057997, -1.6996434 ],
       [ 0.82677586, -0.40438063],
       [ 0.31545529, -0.0708523 ],
       [ 0.28746749, -1.30073171],
       [ 1.19688102, -1.05990808],
       [-1.03703221,  0.36592974],
       [-0.86376885, -0.42878969],
       [ 1.30665474, -1.00638951],
       [-0.95163408,  0.51177695],
       [-0.69716874, -1.45331286],
       [-0.57726552, -0.08831994],
       [ 0.08268704, -0.17551178],
       [ 0.60140761,  1.2877491 ],
       [ 1.68922166, -0.5243832 ],
       [-0.20656276, -0.57467488],
       [ 2.23400659, -1.57666098],
       [ 3.05818465,

In [22]:
y

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1])

In [23]:
x.shape

(100, 2)

In [24]:
y.shape

(100,)

In [26]:
## train test split of the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size  = 0.25,random_state = 42)

In [27]:
x_train

array([[ 0.28746749, -1.30073171],
       [-0.20471637, -0.53424396],
       [ 2.62576537, -2.05613416],
       [-1.97630546, -1.17946953],
       [-0.82089426,  1.4596103 ],
       [ 1.59906828,  1.32303942],
       [ 0.26169267, -0.66298453],
       [-0.28727735, -0.02915044],
       [ 3.05818465, -1.73315167],
       [-0.9888926 ,  1.4100222 ],
       [ 1.4244102 ,  1.66694584],
       [-1.5452034 , -1.23386358],
       [-0.96426779,  0.92643724],
       [ 2.37434003,  2.03642901],
       [ 1.19688102, -1.05990808],
       [-1.44152611, -1.13757447],
       [-0.87330365,  1.12962312],
       [ 1.34455142,  1.20946882],
       [ 1.30012614, -0.62704745],
       [ 2.23400659, -1.57666098],
       [ 1.30665474, -1.00638951],
       [-3.12238639, -1.66813985],
       [ 1.68922166, -0.5243832 ],
       [ 2.38881139, -0.25903227],
       [ 0.82677586, -0.40438063],
       [ 0.60140761,  1.2877491 ],
       [-0.72144086,  2.44982522],
       [-1.03703221,  0.36592974],
       [ 2.87061492,

In [28]:
x_test

array([[-0.69917071,  2.01569513],
       [ 0.60499459,  0.31910418],
       [-1.07328605,  0.20173815],
       [ 2.43176338, -1.60468234],
       [-1.01916133,  1.23548005],
       [-0.74292721,  2.18063222],
       [-0.57726552, -0.08831994],
       [-0.79817653,  2.28878868],
       [-1.09171047,  0.72347664],
       [-1.27504485,  1.08767536],
       [-0.86376885, -0.42878969],
       [-1.09653475,  0.45776402],
       [ 1.55812625,  1.61427432],
       [-1.02534663, -0.87096504],
       [ 1.45077256, -0.96534165],
       [ 0.55321372,  0.93214164],
       [-3.0143753 , -1.49647904],
       [ 2.42114265,  2.56418862],
       [ 1.79057997, -1.6996434 ],
       [ 1.1042068 , -1.46305029],
       [-1.86706107, -1.23109022],
       [-3.59365304, -1.7675401 ],
       [-0.20656276, -0.57467488],
       [ 0.8833059 ,  0.05517063],
       [ 1.53866663, -1.17304966]])

In [29]:
y_train

array([1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0])

In [30]:
y_test

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0])

In [31]:
x_train.shape

(75, 2)

In [32]:
x_test.shape

(25, 2)

In [33]:
y_train.shape

(75,)

In [34]:
y_test.shape

(25,)

In [35]:
from sklearn.svm import SVC

In [36]:
svc = SVC(kernel = "linear")

In [37]:
svc

SVC(kernel='linear')

In [39]:
svc.fit(x_train,y_train)

SVC(kernel='linear')

In [40]:
svc.coef_

array([[-0.39885488,  1.49674171]])

In [41]:
y_pred = svc.predict(x_test)

In [42]:
y_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0])

In [43]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
confusion_matrix = confusion_matrix(y_test,y_pred)
accuracy_score = accuracy_score(y_test,y_pred)
classification_report = classification_report(y_test,y_pred)

In [44]:
confusion_matrix

array([[12,  0],
       [ 0, 13]])

In [45]:
accuracy_score

1.0

In [46]:
classification_report

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        12\n           1       1.00      1.00      1.00        13\n\n    accuracy                           1.00        25\n   macro avg       1.00      1.00      1.00        25\nweighted avg       1.00      1.00      1.00        25\n'

In [47]:
## Hyperparameter tuning
from sklearn.model_selection import GridSearchCV
import warnings 
warnings.filterwarnings("ignore")

In [48]:
param_grid = {
    "C":[0.1,1,10,100,1000],
    "gamma":[1,0.1,0.01,0.001,0.0001],
    "kernel":["linear"]
}

In [50]:
svc = SVC(kernel = "linear")

In [53]:
gridcv = GridSearchCV(svc,param_grid = param_grid,refit = True,cv = 5, verbose = 3)

In [54]:
gridcv

GridSearchCV(cv=5, estimator=SVC(kernel='linear'),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear']},
             verbose=3)

In [55]:
gridcv.fit(x_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.933 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=1, kernel=linear;, score=1.000 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.867 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.867 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=1, kernel=linear;, score=0.933 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.933 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.867 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.867 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.1, kernel=linear;, score=0.933 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=0.01, kernel=linear;, score=0.933 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.01, kernel=linear

GridSearchCV(cv=5, estimator=SVC(kernel='linear'),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear']},
             verbose=3)

In [56]:
y_pred1 = gridcv.predict(x_test)

In [57]:
y_pred1

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0])

In [58]:
gridcv.best_params_

{'C': 0.1, 'gamma': 1, 'kernel': 'linear'}

In [59]:
svc = SVC(C = 0.1,gamma = 1,kernel = "linear")

In [60]:
svc

SVC(C=0.1, gamma=1, kernel='linear')

In [61]:
svc.fit(x_train,y_train)

SVC(C=0.1, gamma=1, kernel='linear')

In [62]:
y_pred2 = svc.predict(x_test)

In [63]:
y_pred2

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0])

In [64]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
confusion_matrix = confusion_matrix(y_test,y_pred2)
accuracy_score = accuracy_score(y_test,y_pred2)
classification_report = classification_report(y_test,y_pred2)

In [65]:
confusion_matrix

array([[12,  0],
       [ 0, 13]])

In [66]:
accuracy_score

1.0

In [67]:
classification_report 

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        12\n           1       1.00      1.00      1.00        13\n\n    accuracy                           1.00        25\n   macro avg       1.00      1.00      1.00        25\nweighted avg       1.00      1.00      1.00        25\n'

In [ ]:
Q3. How does increasing the value of epsilon affect the number of support vectors in SVR?

In Support Vector Regression (SVR), the parameter epsilon (ε) determines the width of the margin around the predicted values within which no penalty is associated with the errors. It is a crucial parameter that influences the trade-off between the smoothness of the regression curve and the accuracy of the fit.

Here's how increasing the value of epsilon affects the number of support vectors in SVR:

Larger Epsilon (Wider Tube):
    A larger epsilon results in a wider tube around the regression line.
    The wider tube allows for more data points to be within the margin without incurring a penalty.
    Consequently, more data points may be treated as non-support vectors.
Smaller Epsilon (Narrower Tube):
    A smaller epsilon results in a narrower tube around the regression line.
    The narrower tube enforces a stricter fit, penalizing data points that fall outside the margin.
    This may lead to fewer support vectors, as the algorithm aims to fit the data more closely.

Increasing epsilon tends to increase the number of points considered within the permissible margin, leading to potentially more non-support vectors. It allows for a more flexible fit, accepting a higher level of error for points within the wider tube. Conversely, a smaller epsilon results in a more rigid fit, potentially reducing the number of support vectors as the algorithm enforces a tighter margin around the regression line.

In [ ]:
Q4. How does the choice of kernel function, C parameter, epsilon parameter, and gamma parameter
affect the performance of Support Vector Regression (SVR)? Can you explain how each parameter works
and provide examples of when you might want to increase or decrease its value?

In [ ]:
Support Vector Regression (SVR) has several parameters that can significantly impact its performance. Here's an explanation of the key parameters and how they affect SVR, along with examples of when you might want to adjust their values:

1.Kernel Function:
   Explanation: 
      The kernel function determines the mapping of the input features into a higher-dimensional space. Common choices include linear, polynomial, radial basis function (RBF), and sigmoid.
   Impact: 
       The choice of the kernel affects the flexibility of the SVR model. For example, the RBF kernel is more flexible and can capture complex relationships, but it may be prone to overfitting.

In [4]:
from sklearn.svm import SVR

# RBF kernel (default)
svr_rbf = SVR(kernel='rbf')

# Linear kernel
svr_linear = SVR(kernel='linear')


In [2]:
svr_rbf

SVR()

In [3]:
svr_linear

SVR(kernel='linear')

In [ ]:
2.C Parameter:
 Explanation: 
    The C parameter trades off correct classification of training points against maximizing the decision function's margin.
 Impact: 
    A smaller C encourages a larger margin and a simpler decision function, possibly allowing more errors. A larger C penalizes errors more heavily, leading to a more complex decision function that closely fits the training data.

In [5]:
# Default C value is 1.0
svr_default = SVR()

# Larger C value
svr_high_C = SVR(C=10.0)

# Smaller C value
svr_low_C = SVR(C=0.1)

In [6]:
svr_default

SVR()

In [7]:
svr_high_C

SVR(C=10.0)

In [8]:
svr_low_C

SVR(C=0.1)

In [ ]:
3.Epsilon Parameter (ε):
 Explanation: 
    Epsilon determines the width of the epsilon-insensitive tube within which no penalty is applied to errors.
 Impact: 
    A larger epsilon allows more training points to be within the tube, affecting the flexibility of the model. A smaller epsilon enforces a stricter fit.

In [10]:
# Default epsilon value is 0.1
svr_default_epsilon = SVR()

# Larger epsilon
svr_large_epsilon = SVR(epsilon=0.2)

# Smaller epsilon
svr_small_epsilon = SVR(epsilon=0.05)

In [11]:
svr_default_epsilon

SVR()

In [12]:
svr_large_epsilon

SVR(epsilon=0.2)

In [13]:
svr_small_epsilon

SVR(epsilon=0.05)

In [ ]:
4.Gamma Parameter:
 Explanation: 
    For RBF, poly, and sigmoid kernels, gamma defines how far the influence of a single training example reaches. Low values mean 'far,' and high values mean 'close.'
 Impact: 
    A small gamma creates a broader decision region, while a large gamma makes the decision region tighter and focuses on individual data points.

In [14]:
# Default gamma value is 'scale'
svr_default_gamma = SVR(kernel='rbf')

# Larger gamma
svr_high_gamma = SVR(kernel='rbf', gamma=0.1)

# Smaller gamma
svr_low_gamma = SVR(kernel='rbf', gamma=0.01)

In [15]:
svr_default_gamma

SVR()

In [16]:
svr_high_gamma

SVR(gamma=0.1)

In [17]:
svr_low_gamma

SVR(gamma=0.01)

In [ ]:
When to Adjust Parameters:

If your model is too complex and overfitting, you might increase C or decrease the gamma parameter.
If your model is too simple and underfitting, you might decrease C or increase the gamma parameter.
Adjust epsilon based on your tolerance for errors within the tube.

In [ ]:
Q5. Assignment:
L Import the necessary libraries and load the dataseg
L Split the dataset into training and testing setZ
L Preprocess the data using any technique of your choice (e.g. scaling, normaliMationK
L Create an instance of the SVC classifier and train it on the training datW
L hse the trained classifier to predict the labels of the testing datW
L Evaluate the performance of the classifier using any metric of your choice (e.g. accuracy,
precision, recall, F1-scoreK
L Tune the hyperparameters of the SVC classifier using GridSearchCV or RandomiMedSearchCV to
improve its performanc_
L Train the tuned classifier on the entire dataseg
L Save the trained classifier to a file for future use.

In [68]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [69]:
from sklearn.datasets import load_iris

In [70]:
dataset = load_iris()

In [71]:
dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [72]:
## Dependent and independent features
x= dataset.data
y = dataset.target

In [73]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [74]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [75]:
## train test split of the dataset
from sklearn.model_selection import train_test_split

In [76]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [77]:
x_train

array([[4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [6.4, 3.2, 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [6.3, 2.8, 5.1, 1.5],
       [6.4, 3.1, 5.5, 1.8],
       [6.6, 3. , 4.4, 1.4],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2

In [78]:
x_test

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [6.5, 3.2, 5.1, 2. ],
       [4.8, 3. , 1.4, 0.1],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.8, 1.5, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.5, 3. , 5.8, 2.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.8, 4.5, 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 2.8, 5.6, 2.1],
       [7.9, 3.8, 6.4, 2. ],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [4.8, 3. , 1.4, 0.3],
       [4.8, 3.1, 1.6, 0.2]])

In [79]:
y_train

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [80]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [81]:
x_train.shape

(120, 4)

In [82]:
x_test.shape

(30, 4)

In [83]:
y_train.shape

(120,)

In [84]:
y_test.shape

(30,)

In [85]:
## Standardization 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [86]:
scaler

StandardScaler()

In [87]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [88]:
x_train

array([[-1.47393679,  1.20365799, -1.56253475, -1.31260282],
       [-0.13307079,  2.99237573, -1.27600637, -1.04563275],
       [ 1.08589829,  0.08570939,  0.38585821,  0.28921757],
       [-1.23014297,  0.75647855, -1.2187007 , -1.31260282],
       [-1.7177306 ,  0.30929911, -1.39061772, -1.31260282],
       [ 0.59831066, -1.25582892,  0.72969227,  0.95664273],
       [ 0.72020757,  0.30929911,  0.44316389,  0.4227026 ],
       [-0.74255534,  0.98006827, -1.27600637, -1.31260282],
       [-0.98634915,  1.20365799, -1.33331205, -1.31260282],
       [-0.74255534,  2.32160658, -1.27600637, -1.44608785],
       [-0.01117388, -0.80864948,  0.78699794,  0.95664273],
       [ 0.23261993,  0.75647855,  0.44316389,  0.55618763],
       [ 1.08589829,  0.08570939,  0.55777524,  0.4227026 ],
       [-0.49876152,  1.87442714, -1.39061772, -1.04563275],
       [-0.49876152,  1.4272477 , -1.27600637, -1.31260282],
       [-0.37686461, -1.47941864, -0.01528151, -0.24472256],
       [ 0.59831066, -0.

In [89]:
x_test

array([[ 0.35451684, -0.58505976,  0.55777524,  0.02224751],
       [-0.13307079,  1.65083742, -1.16139502, -1.17911778],
       [ 2.30486738, -1.0322392 ,  1.8185001 ,  1.49058286],
       [ 0.23261993, -0.36147005,  0.44316389,  0.4227026 ],
       [ 1.2077952 , -0.58505976,  0.61508092,  0.28921757],
       [-0.49876152,  0.75647855, -1.27600637, -1.04563275],
       [-0.2549677 , -0.36147005, -0.07258719,  0.15573254],
       [ 1.32969211,  0.08570939,  0.78699794,  1.49058286],
       [ 0.47641375, -1.92659808,  0.44316389,  0.4227026 ],
       [-0.01117388, -0.80864948,  0.09932984,  0.02224751],
       [ 0.84210448,  0.30929911,  0.78699794,  1.09012776],
       [-1.23014297, -0.13788033, -1.33331205, -1.44608785],
       [-0.37686461,  0.98006827, -1.39061772, -1.31260282],
       [-1.10824606,  0.08570939, -1.27600637, -1.44608785],
       [-0.86445224,  1.65083742, -1.27600637, -1.17911778],
       [ 0.59831066,  0.53288883,  0.55777524,  0.55618763],
       [ 0.84210448, -0.

In [90]:
## model trainig
from sklearn.svm import SVC

In [91]:
svc = SVC(kernel = "poly")

In [92]:
svc

SVC(kernel='poly')

In [93]:
svc.fit(x_train,y_train)

SVC(kernel='poly')

In [94]:
y_pred = svc.predict(x_test)

In [95]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0])

In [99]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
confusion_matrix = confusion_matrix(y_test,y_pred)
accuracy_score = accuracy_score(y_test,y_pred)
classification_report = classification_report(y_test,y_pred)

In [100]:
confusion_matrix 

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  1, 10]])

In [101]:
accuracy_score

0.9666666666666667

In [102]:
classification_reprot 

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        10\n           1       0.90      1.00      0.95         9\n           2       1.00      0.91      0.95        11\n\n    accuracy                           0.97        30\n   macro avg       0.97      0.97      0.97        30\nweighted avg       0.97      0.97      0.97        30\n'

In [103]:
## Hyperparameter tuning
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings("ignore")

In [104]:
param_grid = {"C" :[0.1,1,10,100,1000],
              "gamma":[1,0.1,0.01,0.001,0.0001],
              "kernel":['poly']
}

In [105]:
gridcv = GridSearchCV(svc,param_grid = param_grid,cv = 5,refit = True,verbose = 3) 

In [106]:
gridcv

GridSearchCV(cv=5, estimator=SVC(kernel='poly'),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['poly']},
             verbose=3)

In [107]:
gridcv.fit(x_train,y_train)


Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.958 total time=   0.0s
[CV 2/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.958 total time=   0.0s
[CV 3/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.875 total time=   0.0s
[CV 4/5] END .......C=0.1, gamma=1, kernel=poly;, score=1.000 total time=   0.0s
[CV 5/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.917 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.833 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.333 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.375 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.333 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.333 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=0.01, kernel=poly;, score=0.833 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=0.01, kernel=poly

GridSearchCV(cv=5, estimator=SVC(kernel='poly'),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['poly']},
             verbose=3)

In [108]:
y_pred1 = gridcv.predict(x_test)

In [109]:
y_pred1

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0])

In [111]:
gridcv.best_params_

{'C': 0.1, 'gamma': 1, 'kernel': 'poly'}

In [121]:
svc = SVC(C=0.1,gamma=1,kernel='poly')

In [122]:
svc

SVC(C=0.1, gamma=1, kernel='poly')

In [123]:
svc.fit(x_train,y_train)

SVC(C=0.1, gamma=1, kernel='poly')

In [124]:
y_pred = svc.predict(x_test)

In [125]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0])

In [126]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
confusion_matrix = confusion_matrix(y_test,y_pred)
accuracy_score = accuracy_score(y_test,y_pred)
classification_reprot = classification_report(y_test,y_pred)

In [127]:
confusion_matrix

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  1, 10]])

In [128]:
accuracy_score

0.9666666666666667

In [129]:
classification_reprot 

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        10\n           1       0.90      1.00      0.95         9\n           2       1.00      0.91      0.95        11\n\n    accuracy                           0.97        30\n   macro avg       0.97      0.97      0.97        30\nweighted avg       0.97      0.97      0.97        30\n'

In [132]:
##Save the trained classifier to a file for future use
import joblib
joblib.dump(svc, 'svc.joblib')

['svc.joblib']